name: KeepRenderAwake
on:
  schedule:
    # ogni 14 minuti (Render si addormenta dopo 15)
    - cron: '*/12 * * * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: curl ledwall-portal
        run: |
          curl -fsSL https://ledwall-portal.onrender.com/ || true
